In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from sklearn.linear_model import SGDRegressor

In [2]:
A = np.array([[1,2],[4,3], [5,6]])
A

array([[1, 2],
       [4, 3],
       [5, 6]])

In [3]:
A.shape

(3, 2)

In [9]:
B = A.T
B

array([[1, 4, 5],
       [2, 3, 6]])

In [10]:
B.shape

(2, 3)

In [12]:
C = np.array([[1,3],[4,4],[8,8]])
A + C

array([[ 2,  5],
       [ 8,  7],
       [13, 14]])

In [16]:
D = np.ones((3,3))
D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#produit matriciel
B.dot(D)

array([[10., 10., 10.],
       [11., 11., 11.]])